const fs = require('fs');
const path = require('path');

const files = {
  "docs/1. Ideation Phase/Brainstorm_Idea_Prioritization.md": `# Brainstorm Idea Prioritization\n\n## Ideas for Nutrition Assistant\n1. AI Meal Recognition (High Priority)\n2. Grocery List Auto-generation (High Priority)\n3. Dietitian Consultations (Medium Priority)\n4. Social Challenges (Low Priority)`,
  "docs/1. Ideation Phase/Empathy_Map_Canvas.md": `# Empathy Map Canvas\n\n**User Persona**: Health-conscious busy professional.\n\n- **Thinks & Feels**: Wants to eat healthy but feels overwhelmed by tracking.\n- **Hears**: Advice on trendy diets that are hard to follow.\n- **Sees**: Complicated fitness apps with too much data entry.\n- **Says & Does**: Skips meals, resorts to fast food, wants a simple tracker.\n- **Pains**: Lack of time, confusion over macros.\n- **Gains**: Simple visual tracking, easy recipe suggestions.`,
  "docs/1. Ideation Phase/Problem_Statements.md": `# Problem Statements\n\n1. **Problem**: Users find it tedious to manually enter every ingredient for their meals.\n   **Solution**: Quick-log features and saved custom meals.\n2. **Problem**: Users struggle to know what to eat to meet their specific macro goals.\n   **Solution**: Tailored recipe recommendations based on daily remaining macros.`,
  "docs/2. Requirement Analysis/Customer_Journey_Map.md": `# Customer Journey Map\n\n1. **Discovery**: Hears about the app from a fitness blog.\n2. **Onboarding**: Signs up, enters body metrics and goals (e.g., Lose weight, 2000 kcal/day).\n3. **Daily Use**: Logs breakfast, checks remaining macros, gets a lunch recommendation.\n4. **Retention**: Weekly check-ins, consults with a professional when hitting a plateau.`,
  "docs/2. Requirement Analysis/Data_Flow_Diagrams_and_User_Stories.md": `# Data Flow Diagrams and User Stories\n\n## User Stories\n- As a user, I want to log my meals so I can track my daily caloric intake.\n- As a user, I want to see personalized recipe suggestions to help me meet my macro goals.\n\n## Data Flow\nUser -> Frontend -> API Gateway -> Meals/Users/Recipes Services -> Database`,
  "docs/2. Requirement Analysis/Solution_Requirements.md": `# Solution Requirements\n\n## Functional Requirements\n- User authentication and authorization.\n- Meal logging with macro calculations.\n- Goal setting and progress tracking.\n\n## Non-Functional Requirements\n- Fast load times (< 2 seconds).\n- Responsive design for mobile and desktop.\n- Secure data storage.`,
  "docs/2. Requirement Analysis/Technology_Stack.md": `# Technology Stack\n\n- **Frontend**: React.js, React Router, Context API\n- **Backend**: Node.js, Express.js (Assumed based on proxy config)\n- **Database**: Prisma ORM (Assumed based on package.json)\n- **Styling**: Vanilla CSS with CSS Variables`,
  "docs/3. Project Design Phase/Problem - Solution Fit Template/Problem_Solution_Fit.md": `# Problem - Solution Fit\n\n| Problem | Proposed Solution Feature |\n|---------|---------------------------|\n| Time-consuming tracking | Quick add, barcode scanning (future) |\n| Lack of nutritional knowledge | Educational articles, Consultations |\n| Meal planning difficulty | Personalized recipe recommendations |`,
  "docs/3. Project Design Phase/Proposed Solution/Proposed_Solution.md": `# Proposed Solution\n\nThe Nutrition Assistant is a comprehensive web application designed to simplify diet tracking. It goes beyond simple calorie counting by offering tailored recipe recommendations, direct access to health professionals, and educational resources.`,
  "docs/3. Project Design Phase/Solution Architecture/Solution_Architecture.md": `# Solution Architecture\n\nThe application follows a classic client-server architecture.\n- **Client**: React SPA hosted on static hosting.\n- **API**: RESTful API built with Express.\n- **Data Layer**: Relational database accessed via Prisma ORM.`,
  "docs/4. Project Planning Phase/Planning_logic.md": `# Planning Logic\n\n- **Phase 1**: Core tracking (Authentication, Dashboard, Meal Logging) - *Completed*\n- **Phase 2**: Expansion (Recipes, Food Database, Grocery Lists) - *Completed*\n- **Phase 3**: Premium Features (Consultations, Education) - *Completed*\n- **Phase 4**: Polish and QA - *In Progress*`,
  "docs/4. Project Planning Phase/Project_Planning_Template.md": `# Project Planning Template\n\n**Project Timeline**: 12 weeks\n**Resources**: 1 Frontend Dev, 1 Backend Dev, 1 UI/UX Designer\n**Key Milestones**: Beta Release, UAT, Production Launch`,
  "docs/5. Project Development Phase/Performance Testing/GenAI_Functional_Performance_Testing.md": `# Functional & Performance Testing\n\n- **API Latency**: Target < 200ms for standard requests.\n- **Frontend Render Time**: Target < 1.5s for Time to Interactive (TTI).\n- **Load Testing**: Support up to 1000 concurrent users logging meals simultaneously.`,
  "docs/5. Project Development Phase/User Acceptance Testing/UAT_Report_Template.md": `# UAT Report Template\n\n**Tester Name**: \n**Date**: \n\n| Feature | Expected Result | Actual Result | Pass/Fail |\n|---------|-----------------|---------------|-----------|\n| Registration | User account created and redirected to dashboard | | |\n| Log Meal | Meal appears in today's log and dashboard updates | | |`,
  "docs/6. Project Testing/Nutrition_App_Testing_Document.md": `# Testing Document\n\nComprehensive test cases for all modules including unit tests for utility functions, integration tests for API endpoints, and E2E tests for critical user flows like meal logging and registration.`,
  "docs/7. Project Documentation/Final_Report_Template.md": `# Final Report\n\n**Executive Summary**\nThe Nutrition Assistant project successfully delivered a working MVP that allows users to track their diet, discover recipes, and consult with professionals.\n\n**Lessons Learned**\n- Importance of a normalized food database.\n- User feedback on UI complexity.`,
  "docs/8. Project Demonstration/Nutrition_App_Project_Demonstration.md": `# Project Demonstration Script\n\n1. **Intro**: Welcome to the Nutrition Assistant.\n2. **Onboarding**: Show the registration flow and goal setting.\n3. **Dashboard**: Highlight the daily progress bars and water tracker.\n4. **Meal Logging**: Demonstrate adding a custom meal.\n5. **Recipes**: Show tailored recommendations based on remaining macros.\n6. **Outro**: Discuss future roadmap.`,
  "docs/9. Source Code or Data/README.md": `# Source Code\n\nSource code is maintained in the root directory. Please refer to the main repository \`README.md\` for setup and installation instructions.`
};

for (const [filepath, content] of Object.entries(files)) {
  const fullPath = path.join('d:/nutrition', filepath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content, 'utf8');
}
console.log('Done creating markdown files!');
